# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('a_value', models.FloatField(verbose_name='A value')),
                ('b_value', models.FloatField(verbose_name='B value')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitedata', to='sites.Site')),
            ],
        ),
    ]
